CREATE TABLE `usuarios` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `usuario` varchar(50) DEFAULT NULL,
  `nombre` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `nombres` varchar(100) DEFAULT NULL,
  `apellidos` varchar(100) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `telefono` varchar(20) DEFAULT NULL,
  `rol` enum('super-admin','admin-campana','coordinador','colaborador','veedor') NOT NULL DEFAULT 'colaborador',
  `tipo_usuario` varchar(20) DEFAULT 'consulta',
  `colaborador_id` int(11) DEFAULT NULL,
  `documento_colaborador` varchar(20) DEFAULT NULL,
  `avatar_url` varchar(500) DEFAULT NULL,
  `estado` enum('activo','inactivo','suspendido') NOT NULL DEFAULT 'activo',
  `ultimo_acceso` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `activo` tinyint(1) DEFAULT 1,
  `intentos_fallidos` int(11) DEFAULT 0,
  `bloqueado_hasta` timestamp NULL DEFAULT NULL,
  `require_2fa` tinyint(1) DEFAULT 0,
  `token_2fa` varchar(255) DEFAULT NULL,
  `reset_token` varchar(255) DEFAULT NULL,
  `reset_token_expira` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `usuario` (`usuario`),
  KEY `idx_rol` (`rol`),
  KEY `idx_estado` (`estado`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `colaboradores` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campana_id` int(11) NOT NULL,
  `nombres` varchar(100) NOT NULL,
  `apellidos` varchar(100) NOT NULL,
  `tipo_documento` enum('CC','TI','CE','PA','RC','NIT') DEFAULT 'CC',
  `documento` varchar(20) NOT NULL,
  `fecha_nacimiento` date NOT NULL,
  `genero` varchar(20) DEFAULT 'Otro',
  `perfil` varchar(100) DEFAULT 'Simpatizante',
  `nivel_liderazgo` int(11) DEFAULT 0,
  `nivel_participacion` enum('Simpatizante','Aportante','Activista de Opinion','Movilizador','Contradictor','Contratista') DEFAULT NULL,
  `areas_interes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`areas_interes`)),
  `dato_potencial` int(11) DEFAULT 0,
  `dato_historico` int(11) DEFAULT 0,
  `estado` varchar(20) DEFAULT 'Nuevo',
  `revision` datetime DEFAULT NULL,
  `departamento` varchar(100) NOT NULL,
  `municipio` varchar(100) NOT NULL,
  `tipo_territorio` varchar(50) DEFAULT NULL,
  `territorio` varchar(100) DEFAULT NULL,
  `barrio` varchar(100) DEFAULT NULL,
  `territorio_id` int(11) DEFAULT NULL,
  `direccion` varchar(255) DEFAULT NULL,
  `detalle_ubicacion` text DEFAULT NULL,
  `lider_directo` varchar(20) DEFAULT NULL COMMENT 'Documento del lider',
  `email` varchar(255) NOT NULL,
  `telefono` varchar(20) NOT NULL,
  `telefono_whatsapp` varchar(20) NOT NULL,
  `observaciones` text DEFAULT NULL,
  `usuario_registro_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `puesto_votacion` varchar(255) DEFAULT NULL COMMENT 'Nombre del puesto de votacion',
  `mesa_votacion` varchar(10) DEFAULT NULL COMMENT 'Numero de mesa',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_doc_camp` (`documento`,`campana_id`),
  KEY `idx_campana` (`campana_id`),
  KEY `idx_perfil` (`perfil`),
  KEY `idx_lider` (`lider_directo`),
  KEY `idx_territorio` (`departamento`,`municipio`),
  KEY `idx_jerarquia` (`campana_id`,`lider_directo`,`documento`),
  KEY `idx_territorio_campana` (`campana_id`,`departamento`,`municipio`),
  KEY `idx_puesto_mesa` (`campana_id`,`puesto_votacion`,`mesa_votacion`)
) ENGINE=InnoDB AUTO_INCREMENT=1119 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `puestos_votacion` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `departamento` varchar(100) NOT NULL,
  `municipio` varchar(100) NOT NULL,
  `cod_mpio` varchar(10) DEFAULT NULL,
  `puesto` varchar(255) NOT NULL,
  `comuna` varchar(100) DEFAULT NULL,
  `direccion` varchar(255) DEFAULT NULL,
  `latitud` decimal(10,8) DEFAULT NULL,
  `longitud` decimal(11,8) DEFAULT NULL,
  `estado` enum('Activo','Inactivo') DEFAULT 'Activo',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_municipio` (`municipio`),
  KEY `idx_departamento` (`departamento`),
  KEY `idx_puesto` (`puesto`),
  KEY `idx_cod_mpio` (`cod_mpio`)
) ENGINE=InnoDB AUTO_INCREMENT=1127 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `reportes_diaD` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_campaña` varchar(20) DEFAULT '02',
  `id_colaborador` int(11) NOT NULL,
  `id_puesto` int(11) DEFAULT NULL,
  `id_mesa` int(11) DEFAULT NULL,
  `votos_nuevos` int(11) NOT NULL,
  `votos_total` int(11) NOT NULL,
  `timestamp` timestamp NULL DEFAULT current_timestamp(),
  `certificado_url` varchar(255) DEFAULT NULL,
  `estado_semaforo` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_reportes_colaborador` (`id_colaborador`),
  CONSTRAINT `fk_reportes_colaborador` FOREIGN KEY (`id_colaborador`) REFERENCES `colaboradores` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

